In [1]:
from auto_reduce import *
import numpy as np

## System object attributes

In [2]:
# Create symbolic objects
x, f, P = system.load_ODE_model(2, 2)
f[0] = -x[0]**2 + P[0]*x[1]
f[1] = -P[1]*x[1]
print('The states : {0}'.format(x))
print('The dynamics f : {0}'.format(f))
print('The dynamics P : {0}'.format(P))
C = np.array([[0,1]]).tolist()

The states : [x0, x1]
The dynamics f : [P0*x1 - x0**2, -P1*x1]
The dynamics P : [P0, P1]


In [3]:
# System class
sys = System(x, f, params = P, C = C)

## Solve the System using the ODE subclass 

In [4]:
# Solve ODE from System
from auto_reduce.ode import ODE
timepoints = np.linspace(0,20,100)
sys.params_values = [2, 4]
sys.x_init = [0,10]
sys_ode = ODE(sys.x, sys.f, params = sys.params, params_values = sys.params_values,
              C = sys.C, x_init = sys.x_init, timepoints = timepoints)
solution = sys_ode.solve_system()

## Local sensitivity analysis tools for System using the SSM subclass

In [6]:
# Solve for sensitivity analysis from System
from auto_reduce.local_sensitivity import SSM
timepoints = np.linspace(0,20,10)
sys.params_values = [2, 4]
sys.x_init = [0,10]
sys_ssm = SSM(sys.x, sys.f, params = sys.params, params_values = sys.params_values,
              C = sys.C, x_init = sys.x_init, timepoints = timepoints)
solution = sys_ssm.compute_SSM()

In [8]:
J = sys_ssm.compute_J([2,1])
Z = sys_ssm.compute_Zj([2,1], 1)
print('J = ',J)
print('Z = ', Z)
print('SSM = ',solution)

J =  [[-2.06  1.  ]
 [ 0.   -2.  ]]
Z =  [ 0.  -0.5]
SSM =  [[[ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  8.69364527e-16]
  [ 0.00000000e+00 -3.89172132e-02]]

 [[-3.77646620e-15  1.57845580e-15]
  [-2.28944359e-02 -2.31602197e-02]]

 [[ 7.53560282e-15 -3.77234807e-14]
  [-1.64068719e-02 -1.64049439e-02]]

 [[ 2.10870174e-13  2.33379896e-13]
  [-1.26987361e-02 -1.26914397e-02]]

 [[ 7.22811143e-18  7.22811185e-18]
  [-3.46150911e-04 -3.46150917e-04]]

 [[-4.88537330e-18 -3.13744454e-17]
  [-5.99483480e-07 -8.28480297e-09]]

 [[ 0.00000000e+00  0.00000000e+00]
  [-6.64224589e-07  3.37215043e-07]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 2.53139779e-07 -8.84140998e-08]]

 [[ 0.00000000e+00  0.00000000e+00]
  [-5.96627933e-07 -4.73660306e-09]]]


## Use Reduce class to perform model reduction of System 

In [11]:
from auto_reduce.model_reduction import Reduce
timepoints_ode = np.linspace(0,20,100)
timepoints_ssm = np.linspace(0,20,10)
sys_reduce = Reduce(sys.x, sys.f, params = sys.params, params_values = sys.params_values,
        C = sys.C, x_init = sys.x_init, 
       timepoints_ode = timepoints_ode, timepoints_ssm = timepoints_ssm,)


In [20]:
all_combinations = sys_reduce.get_all_combinations()
T, T1, T2 = sys_reduce.get_T([0])

IndexError: index 1 is out of bounds for axis 1 with size 1

[[0], [1]]