In [1]:
from autoreduce import *
import numpy as np

## System object attributes

In [2]:
# Create symbolic objects
x, f, P = load_ODE_model(2, 2)
f[0] = -x[0]**2 + P[0]*x[1]
f[1] = -P[1]*x[1]
print('The states : {0}'.format(x))
print('The dynamics f : {0}'.format(f))
print('The dynamics P : {0}'.format(P))
C = np.array([[0,1]]).tolist()

The states : [x0, x1]
The dynamics f : [P0*x1 - x0**2, -P1*x1]
The dynamics P : [P0, P1]


In [3]:
# System class
sys = System(x, f, params = P, C = C)

## Solve the System using the ODE subclass 

In [4]:
# Solve ODE from System
from autoreduce.ode import ODE
timepoints = np.linspace(0,20,100)
sys.params_values = [2, 4]
sys.x_init = [0,10]
sys_ode = ODE(sys.x, sys.f, params = sys.params, params_values = sys.params_values,
              C = sys.C, x_init = sys.x_init, timepoints = timepoints)
solution = sys_ode.solve_system()

## Local sensitivity analysis tools for System using the SSM subclass

In [5]:
# Solve for sensitivity analysis from System
from autoreduce.local_sensitivity import SSM
timepoints = np.linspace(0,20,10)
sys.params_values = [2, 4]
sys.x_init = [0,10]
sys_ssm = SSM(sys.x, sys.f, params = sys.params, params_values = sys.params_values,
              C = sys.C, x_init = sys.x_init, timepoints = timepoints)
solution = sys_ssm.compute_SSM()

SSM Progress: |██████████████████████████████████████████████████| 100.0% Complete


In [6]:
J = sys_ssm.compute_J([2,1])
Z = sys_ssm.compute_Zj([2,1], 1)
print('J = ',J)
print('Z = ', Z)
print('SSM = ',solution)

J =  [[ 0. -2.]
 [ 0. -2.]]
Z =  [ 0.  -0.5]
SSM =  [[[ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]]

 [[ 1.75024701e-01  2.29836955e-14]
  [ 1.36106614e-01 -3.89180870e-02]]

 [[ 2.05899440e-01  1.03151368e-12]
  [ 1.82738946e-01 -2.31604933e-02]]

 [[ 2.18762852e-01  0.00000000e+00]
  [ 2.02355664e-01 -1.64071878e-02]]

 [[ 2.25816815e-01  0.00000000e+00]
  [ 2.13114620e-01 -1.27021959e-02]]

 [[ 7.66182579e-03  0.00000000e+00]
  [ 7.31704352e-03 -3.44782265e-04]]

 [[ 2.63590284e-10  0.00000000e+00]
  [ 2.53705629e-10 -9.88465494e-12]]

 [[-2.70825331e-09  0.00000000e+00]
  [-2.62120225e-09  8.70510635e-11]]

 [[ 4.10298779e-08  0.00000000e+00]
  [ 3.98759118e-08 -1.15396610e-09]]

 [[ 9.43881879e-09  0.00000000e+00]
  [ 9.20284817e-09 -2.35970616e-10]]]
